updated font and fixed to match eslint
TheAmazingPeleg/FoodDelivery pull request #27
Opened 2023-04-12 15:38 UTC by Br3adMan1

2023-04-12 16:42 UTC, Tamir198 requested changes
Please be consistent with the css styling, you can do 
```
selector{
}
```

or do it like this 
```
selector
{
}
```

But please do not mix 2 different styles of code

2023-04-12 16:44 UTC, Tamir198 requested changes

2023-04-12 16:44 UTC, Tamir198 commented on frontend/src/Components/SearchBar/SearchBar.styling.css
> +}
Please don't use Please dont use `*` like this, try to be more specific with your selector

2023-04-13 09:24 UTC, Itay-Manevych approved these changes
good

2023-04-13 11:03 UTC, merged